apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  namespace: hospital-app
data:
  application.properties: |
    spring.application.name=hospital
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    server.port=8081
    # Database configuration (values will be populated from secrets)
    spring.datasource.url=jdbc:mysql://mysql-service:3306/hospital
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
