apiVersion: v1
kind: Service
metadata:
  name: hospital-service
  namespace: hospital-app
  labels:
    app: hospital-backend
spec:
  type: LoadBalancer
  selector:
    app: hospital-backend
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
