apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital-app
type: Opaque
stringData:
  db-username: root
  db-password: root
  db-root-password: root
  # JWT Secret Key - change this in production
  jwt-secret: your-jwt-secret-key-change-in-production-environment
