apiVersion: v1
kind: ServiceAccount
metadata:
  name: hospital-sa
  namespace: hospital-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hospital-role
  namespace: hospital-app
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hospital-rolebinding
  namespace: hospital-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hospital-role
subjects:
- kind: ServiceAccount
  name: hospital-sa
  namespace: hospital-app
